repos:
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 --config .flake8 app
        language: system
        types: [python]
        pass_filenames: false
