# Generated by Django 5.0.4 on 2024-04-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='source',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
